### ISSUE TITLE
Update Week 5 6 7

### ISSUE THREAD

**Issue by kaliPrasad6400** [suryanshsoni120/100xdevs#8]

**Comment by kaliPrasad6400** [comment]
Brother!! Are you working on it or you need any help?

**Comment by suryanshsoni120** [comment]
Working on it bro. Was stuck in some other work so couldn't update it.

**Comment by MysteryHawk17** [comment]
@nothuman2718 could refer to this if you want 
https://github.com/MysteryHawk17/cohort-assignments

**Comment by kaliPrasad6400** [comment]
Yeah. Definitely will look on to that.
